const NEXT_PUBLIC_FAUCET_API_URL = process.env.NEXT_PUBLIC_FAUCET_API_URL!;
const NEXT_PUBLIC_GELATO_BRIDGE_URL =
  process.env.NEXT_PUBLIC_GELATO_BRIDGE_URL!;

const NEXT_PUBLIC_ENVIRONMENT = process.env.NEXT_PUBLIC_ENVIRONMENT!;
const NEXT_PUBLIC_SENTRY_DSN = process.env.NEXT_PUBLIC_SENTRY_DSN!;
const NEXT_PUBLIC_GTM_ID = process.env.NEXT_PUBLIC_GTM_ID!;
const NEXT_PUBLIC_SEGMENT_WRITE_KEY =
  process.env.NEXT_PUBLIC_SEGMENT_WRITE_KEY!;
const NEXT_PUBLIC_ONE_TRUST_ID = process.env.NEXT_PUBLIC_ONE_TRUST_ID;
const NEXT_PUBLIC_DUNE_API_KEY = process.env.NEXT_PUBLIC_DUNE_API_KEY;
const NEXT_PUBLIC_WC_PROJECT_ID = process.env.NEXT_PUBLIC_WC_PROJECT_ID!;
const NEXT_PUBLIC_HCAPTCHA_SITEKEY = process.env.NEXT_PUBLIC_HCAPTCHA_SITEKEY!;

if (!NEXT_PUBLIC_FAUCET_API_URL && NEXT_PUBLIC_ENVIRONMENT !== "local") {
  throw new Error("Missing environment variable NEXT_PUBLIC_FAUCET_API_URL");
}

if (!NEXT_PUBLIC_GELATO_BRIDGE_URL && NEXT_PUBLIC_ENVIRONMENT !== "local") {
  throw new Error("Missing environment variable NEXT_PUBLIC_GELATO_BRIDGE_URL");
}

if (!NEXT_PUBLIC_SENTRY_DSN && NEXT_PUBLIC_ENVIRONMENT !== "local") {
  throw new Error("Missing environment variable NEXT_PUBLIC_SENTRY_DSN.");
}

if (!NEXT_PUBLIC_GTM_ID && NEXT_PUBLIC_ENVIRONMENT !== "local") {
  throw new Error("Missing environment variable NEXT_PUBLIC_GTM_ID.");
}

if (!NEXT_PUBLIC_SEGMENT_WRITE_KEY && NEXT_PUBLIC_ENVIRONMENT !== "local") {
  throw new Error(
    "Missing environment variable NEXT_PUBLIC_SEGMENT_WRITE_KEY."
  );
}

if (!NEXT_PUBLIC_WC_PROJECT_ID && NEXT_PUBLIC_ENVIRONMENT !== "local") {
  throw new Error("Missing environment variable NEXT_PUBLIC_WC_PROJECT_ID.");
}

export {
  NEXT_PUBLIC_DUNE_API_KEY,
  NEXT_PUBLIC_ENVIRONMENT,
  NEXT_PUBLIC_FAUCET_API_URL,
  NEXT_PUBLIC_GELATO_BRIDGE_URL,
  NEXT_PUBLIC_GTM_ID,
  NEXT_PUBLIC_HCAPTCHA_SITEKEY,
  NEXT_PUBLIC_ONE_TRUST_ID,
  NEXT_PUBLIC_SEGMENT_WRITE_KEY,
  NEXT_PUBLIC_SENTRY_DSN,
  NEXT_PUBLIC_WC_PROJECT_ID,
};
